working BATS with some helpers
added contains_text helper

always checkout, accept either workspace or build steps

readme and help text cleanup

full config test for build-steps parameter

add missing checkout assertion to publish steps

remove inline testing in favor of bats

install BATS

use diff over line by line compare to handle whitespacing issue"

replace external testing with BATS also

remove old runner

diff --git a/src/commands/install.yml b/src/commands/install.yml
--- a/src/commands/install.yml
+++ b/src/commands/install.yml
@@ -2,5 +2,12 @@ steps:
   - run:
       name: Install JFrog CLI
       command: |
-        curl -fL https://getcli.jfrog.io | sh
-        chmod a+x jfrog && sudo mv jfrog /usr/local/bin
+        echo "Checking for existence of CLI"
+        jfrog -v
+        if [ $? -gt 0 ]; then
+          echo "Not found, installing latest"
+          curl -fL https://getcli.jfrog.io | sh
+          chmod a+x jfrog && sudo mv jfrog /usr/local/bin
+        else
+          echo "CLI exists, skipping install"
+        fi
diff --git a/tests/outputs/job-with-spec.yml b/tests/outputs/job-with-spec.yml
--- a/tests/outputs/job-with-spec.yml
+++ b/tests/outputs/job-with-spec.yml
@@ -1,29 +1,21 @@
-#given
-workflows:
-  version: 2
-  test-orb:
-    jobs:
-      - artifactory/upload:
-          name: Test Upload
-          source: test/artifact.jar
-          target: repo/path
-          file-spec: spec.json
-          docker: circleci/another-image:123
-#end given
-
-
-
-#then
-version: 2.1
+version: 2
 jobs:
   Test Upload:
     docker:
-    - image: circleci/another-image:123
+    - image: circleci/openjdk:8
     steps:
+    - checkout
     - run:
         command: |-
-          curl -fL https://getcli.jfrog.io | sh
-          chmod a+x jfrog && sudo mv jfrog /usr/local/bin
+          echo "Checking for existence of CLI"
+          jfrog -v
+          if [ $? -gt 0 ]; then
+            echo "Not found, installing latest"
+            curl -fL https://getcli.jfrog.io | sh
+            chmod a+x jfrog && sudo mv jfrog /usr/local/bin
+          else
+            echo "CLI exists, skipping install"
+          fi
         name: Install JFrog CLI
     - run:
         command: jfrog rt c rt-server-1 --url=${ARTIFACTORY_URL} --apikey=${ARTIFACTORY_API_KEY} --interactive=false
@@ -36,4 +28,3 @@ workflows:
   test-orb:
     jobs:
     - Test Upload
-#end then
